package pglp.orgdir;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    public static void main(String[] args) {
    	Personnel p1 = new Personnel.Builder("clément", "caumes").build();
    	Personnel p2 = new Personnel.Builder("mehdi", "merimi").build();
    	DAO <Personnel> personnelDAO = new PersonnelDAO();
    	personnelDAO.create(p1);
    	personnelDAO.create(p2);
    }
}
